# -*- coding: utf-8 -*-
"""
Regenerate vgc-stock-manager-codemap.md — an index of every function/method in
the plugin, so a cold session can jump straight to the right line instead of
grepping. Run from the project root:

    python vgc-stock-manager-codemap.py

Cheap to run; re-run whenever app.js / the PHP classes move around.
"""
import io, os, re

ROOT = os.path.dirname(os.path.abspath(__file__))
PLUGIN = os.path.join(ROOT, 'vgc-stock-manager')
OUT = os.path.join(ROOT, 'vgc-stock-manager-codemap.md')


def first_comment_above(lines, idx):
    """A purpose hint from the comment above a definition, or '' if there is none.

    Only returns text when the preceding line is genuinely a comment (so code is
    never mistaken for a hint). For a PHP/JS docblock ending in */, it walks up to
    the block's first prose (non-@) line — the summary.
    """
    j = idx - 1
    while j >= 0 and lines[j].strip() == '':
        j -= 1
    if j < 0:
        return ''
    t = lines[j].strip()

    # A docblock close: walk up to the summary line inside it.
    if t == '*/' or t.endswith('*/'):
        k = j
        while k >= 0 and '/**' not in lines[k] and '/*' not in lines[k]:
            k -= 1
        for m in range(k + 1, j + 1):
            body = lines[m].strip().lstrip('*').strip()
            if body and not body.startswith('@') and body not in ('/**', '*/') and not body.endswith('*/'):
                return body[:90]
        return ''

    # A single-line comment.
    if t.startswith('//'):
        return t[2:].strip()[:90]
    if t.startswith('*') and not t.startswith('*/'):
        body = t.lstrip('*').strip()
        return '' if body.startswith('@') else body[:90]
    # Anything else is code — no hint.
    return ''


def index_js(path):
    lines = io.open(path, encoding='utf-8').read().split('\n')
    rows = []      # (line, kind, name, hint)
    sections = []  # (line, title)
    for i, ln in enumerate(lines):
        # banner section headers: /* Screen: Orders ... */ or a line inside a banner
        m = re.search(r'/\*\s*(Screen:[^*]+?)\s*\*/', ln)
        if m:
            sections.append((i + 1, m.group(1).strip()))
        m = re.match(r'\t*(?:Screen|Router|Icons|Shell|i18n)\b.*', ln.strip().lstrip('/* '))
        # named function declarations
        m = re.match(r'\s*function ([A-Za-z0-9_]+)\s*\(([^)]*)\)', ln)
        if m:
            rows.append((i + 1, 'fn', m.group(1) + '(' + m.group(2).strip() + ')', first_comment_above(lines, i)))
            continue
        # assigned function expressions (e.g. viewItemForm = function ...)
        m = re.match(r'\s*(?:var\s+)?([A-Za-z0-9_]+)\s*=\s*function\s*\(([^)]*)\)', ln)
        if m:
            rows.append((i + 1, 'fn=', m.group(1) + '(' + m.group(2).strip() + ')', first_comment_above(lines, i)))
    return rows, sections


def index_php(path):
    lines = io.open(path, encoding='utf-8').read().split('\n')
    rows = []
    cls = None
    for i, ln in enumerate(lines):
        m = re.match(r'\s*(?:abstract\s+|final\s+)?(?:class|trait|interface) ([A-Za-z0-9_]+)', ln)
        if m:
            cls = m.group(1)
            rows.append((i + 1, 'class', cls, ''))
            continue
        m = re.match(r'\s*(?:public|private|protected)\s+(?:static\s+)?function ([A-Za-z0-9_]+)\s*\(([^)]*)\)', ln)
        if m:
            rows.append((i + 1, 'method', m.group(1) + '(' + m.group(2).strip()[:60] + ')', first_comment_above(lines, i)))
    return rows


def main():
    out = []
    out.append('# VGC Stock Manager — code map')
    out.append('')
    out.append('> Generated by `vgc-stock-manager-codemap.py`. Line numbers drift as files change — re-run the script after edits. Purpose hints come from the comment above each definition.')
    out.append('')

    # ---- app.js ----
    jspath = os.path.join(PLUGIN, 'app', 'app.js')
    rows, sections = index_js(jspath)
    out.append('## app/app.js  (the whole SPA)')
    out.append('')
    if sections:
        out.append('### Screens / sections (banner comments)')
        out.append('')
        out.append('| line | section |')
        out.append('|---|---|')
        for line, title in sections:
            out.append('| %d | %s |' % (line, title))
        out.append('')
    out.append('### Functions')
    out.append('')
    out.append('| line | name | purpose |')
    out.append('|---|---|---|')
    for line, kind, name, hint in rows:
        mark = '`' + name + '`' + ('  ⟵reassigned' if kind == 'fn=' else '')
        out.append('| %d | %s | %s |' % (line, mark, hint.replace('|', '\\|')))
    out.append('')

    # ---- PHP ----
    out.append('## PHP classes (includes/)')
    out.append('')
    php_files = []
    for dirpath, _dirs, files in os.walk(os.path.join(PLUGIN, 'includes')):
        for fn in files:
            if fn.endswith('.php'):
                php_files.append(os.path.join(dirpath, fn))
    for full in sorted(php_files, key=lambda p: os.path.relpath(p, os.path.join(PLUGIN, 'includes'))):
        rel = os.path.relpath(full, os.path.join(PLUGIN, 'includes')).replace('\\', '/')
        rows = index_php(full)
        if not rows:
            continue
        out.append('### %s' % rel)
        out.append('')
        out.append('| line | member | purpose |')
        out.append('|---|---|---|')
        for line, kind, name, hint in rows:
            label = ('**' + name + '**') if kind == 'class' else ('`' + name + '`')
            out.append('| %d | %s | %s |' % (line, label, hint.replace('|', '\\|')))
        out.append('')

    io.open(OUT, 'w', encoding='utf-8', newline='').write('\n'.join(out))
    print('wrote', OUT)
    print('app.js functions:', len(index_js(jspath)[0]))


if __name__ == '__main__':
    main()
